# Application Name (STANDARD FORMAT)
spring.application.name=BOOKING-SERVICE

# Server Configuration
server.port=2003

# Eureka Configuration (ENABLE)
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.instance.prefer-ip-address=true
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/bookingdb
spring.datasource.username=postgres
spring.datasource.password=varsh

# JPA / Hibernate Configuration
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Logging Configuration
logging.level.org.springframework=INFO

# FIXED PACKAGE (IMPORTANT)
logging.level.com.gl.project.BookingService=DEBUG

# Show SQL query parameters
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE