spring.application.name=API-GATEWAY
server.port=8081

# Eureka Configuration
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.client.fetch-registry=true
eureka.client.register-with-eureka=true
eureka.instance.prefer-ip-address=true

# Service Discovery Locator
spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true



# Public: Register
spring.cloud.gateway.routes[0].id=user-service-register
spring.cloud.gateway.routes[0].uri=lb://USER-SERVICE
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/users/register
spring.cloud.gateway.routes[0].filters[0]=StripPrefix=0

# Public: Login
spring.cloud.gateway.routes[1].id=user-service-login
spring.cloud.gateway.routes[1].uri=lb://USER-SERVICE
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/users/login
spring.cloud.gateway.routes[1].filters[0]=StripPrefix=0

# Protected User Routes
spring.cloud.gateway.routes[2].id=user-service-protected
spring.cloud.gateway.routes[2].uri=lb://USER-SERVICE
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/users/**
spring.cloud.gateway.routes[2].filters[0]=StripPrefix=0


# BOOKING SERVICE
spring.cloud.gateway.routes[3].id=booking-service
spring.cloud.gateway.routes[3].uri=lb://BOOKING-SERVICE
spring.cloud.gateway.routes[3].predicates[0]=Path=/bookings/**

# PROVIDER SERVICE
spring.cloud.gateway.routes[4].id=provider-service
spring.cloud.gateway.routes[4].uri=lb://PROVIDER-SERVICE
spring.cloud.gateway.routes[4].predicates[0]=Path=/services/**

# Global CORS config
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedOrigins=*
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedMethods=GET,POST,PUT,DELETE,OPTIONS
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedHeaders=*

# Security / JWT
jwt.secret=5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437
jwt.expiration=3600000


