spring.application.name=API-GATEWAY
server.port=8081

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka

# Enable service discovery
spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true

# ROUTES

# USER SERVICE
spring.cloud.gateway.routes[0].id=user-service
spring.cloud.gateway.routes[0].uri=lb://USER-SERVICE
spring.cloud.gateway.routes[0].predicates[0]=Path=/users/**

# BOOKING SERVICE
spring.cloud.gateway.routes[1].id=booking-service
spring.cloud.gateway.routes[1].uri=lb://BOOKING-SERVICE
spring.cloud.gateway.routes[1].predicates[0]=Path=/bookings/**

# PROVIDER SERVICE
spring.cloud.gateway.routes[2].id=provider-service
spring.cloud.gateway.routes[2].uri=lb://PROVIDER-SERVICE
spring.cloud.gateway.routes[2].predicates[0]=Path=/services/**