spring.application.name=ProviderService
server.port=8083

# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/ProviderService
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Disable Eureka (IMPORTANT)
eureka.client.enabled=false
spring.cloud.discovery.enabled=false

# Service Messages
ServiceService.SERVICE_NOT_FOUND=Service not found with ID:
ServiceService.DUPLICATE_SERVICE=Service already exists with name:

# Logging
logging.level.org.springframework=INFO
logging.level.com.gl.project=DEBUG



