# Application Name (USE STANDARD FORMAT)
spring.application.name=PROVIDER-SERVICE

# Server Port
server.port=8083

# Eureka Configuration (ENABLE IT)
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.instance.prefer-ip-address=true
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/providerservicedb
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Service Messages
ServiceService.SERVICE_NOT_FOUND=Service not found with ID:
ServiceService.DUPLICATE_SERVICE=Service already exists with name:

# Logging
logging.level.org.springframework=INFO
logging.level.com.gl.project=DEBUG