spring.application.name=PAYMENT-SERVICE
server.port=8085

#Database
spring.datasource.url=jdbc:postgresql://localhost:5432/paymentsmicroservice
spring.datasource.username=postgres
spring.datasource.password=sid
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# 3. Eureka Client Configuration
# This allows the API Gateway and Booking Service to find the Payment Service
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.instance.prefer-ip-address=true
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# 4. Jackson Serialization (To ensure Enums like Status are handled correctly)
spring.jackson.serialization.write-enums-using-to-string=true
