spring.application.name=REVIEWS-SERVICE


# Server Configuration
server.port=2004

# Eureka Configuration
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.instance.prefer-ip-address=true

# ? ENABLE EUREKA (FIX)
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/ReviewDatabase
spring.datasource.username=postgres
spring.datasource.password=root

# JPA / Hibernate Configuration
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# JWT Configuration
jwt.secret=myCustomSecretKeyForUserServiceProject2024Secure
jwt.expiration=86400000

# Logging
logging.level.org.springframework=INFO
logging.level.com.example.reviews=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# Use relative path (auto-creates logs folder)
logging.file.name=logs/review-service.log